### ISSUE TITLE
error with interceptor "totalrainin"

### ISSUE THREAD

**Issue by Blisk** [matthewwall/weewx-interceptor#113]
I have installed interceptor now 3 times and still the same error, what can be wrong.
weewx version = 4.9.1

Jan  9 13:22:49 web journal[59048]: weewx[59048] INFO weewx.engine: Main loop exiting. Shutting engine down.
Jan  9 13:22:49 web journal[59048]: weewx[59048] INFO user.interceptor: shutting down server thread
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__: Caught unrecoverable exception:
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****  'totalrainin'
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****  Traceback (most recent call last):
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****      engine.run()
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 208, in run
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****      for packet in self.console.genLoopPackets():
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****    File "/usr/share/weewx/user/interceptor.py", line 2557, in genLoopPackets
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****      pkt = self._device.parser.parse(data)
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****    File "/usr/share/weewx/user/interceptor.py", line 2397, in parse
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****      self.LABEL_MAP.pop('totalrainin')
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****  KeyError: 'totalrainin'
Jan  9 13:22:50 web journal[59048]: weewx[59048] CRITICAL __main__:     ****  Exiting.

**Comment by Blisk** [comment]
I solved this error, it was actually problem with mariadb server so I deleted it and install mysql and now it works.
