### ISSUE TITLE
No data on webpage, WS2900

### ISSUE THREAD

**Issue by barcik75** [matthewwall/weewx-interceptor#30]
Hi,
Thanks for great work.
I have problem with my WS. WS is type WS2900.
My WS have IP address 192.168.1.151. My Raspberry-pi where is weewx have IP 192.168.1.150.
I set address redirection from WU to Raspberry. It's works:
`19:36:08.814715 IP 192.168.1.151.4096 > 192.168.1.150.53: 5034+ A? rtupdate.wunderground.com. (43)
19:36:08.817096 IP 192.168.1.150.53 > 192.168.1.151.4096: 5034* 1/0/0 A 192.168.1.150 (59)
19:36:08.825108 IP 192.168.1.151.36414 > 192.168.1.150.80: Flags [S], seq 269468253, win 5840, options [mss 1460], length 0
19:36:08.825698 IP 192.168.1.150.80 > 192.168.1.151.36414: Flags [R.], seq 0, ack 269468254, win 0, length 0`
My weewx are also configured to work with your interceptor:
`Jun 15 19:28:17 raspberry-pi systemd[1]: Started LSB: weewx weather system.
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: driver version is 0.39
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: device type: observer
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: sensor map: None
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: mode is sniff
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: sniff iface=wlan0 promiscuous=0
Jun 15 19:28:17 raspberry-pi weewx[11470]: interceptor: MainThread: sniff filter 'src 192.168.1.151 and dst port 80'
Jun 15 19:28:17 raspberry-pi weewx[11470]: engine: StdConvert target unit is 0x1
Jun 15 19:28:17 raspberry-pi weewx[11470]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Jun 15 19:28:17 raspberry-pi weewx[11470]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Jun 15 19:28:17 raspberry-pi weewx[11470]: engine: Archive will use data binding wx_binding
Jun 15 19:28:17 raspberry-pi weewx[11470]: engine: Record generation will be attempted in 'hardware'
Jun 15 19:28:18 raspberry-pi weewx[11470]: engine: Using archive interval of 30 seconds (specified in weewx configuration)
Jun 15 19:28:18 raspberry-pi weewx[11470]: engine: Archive delay (15) is unusually long
Jun 15 19:28:18 raspberry-pi weewx[11470]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jun 15 19:28:18 raspberry-pi weewx[11470]: manager: Starting backfill of daily summaries
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: StationRegistry: Registration not requested.
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: Wunderground: Posting not enabled.
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: PWSweather: Posting not enabled.
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: CWOP: Posting not enabled.
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: WOW: Posting not enabled.
Jun 15 19:28:18 raspberry-pi weewx[11470]: restx: AWEKAS: Posting not enabled.
Jun 15 19:28:18 raspberry-pi weewx[11470]: engine: Starting up weewx version 3.8.0
Jun 15 19:28:18 raspberry-pi weewx[11470]: engine: Starting main packet loop.
Jun 15 19:29:36 raspberry-pi systemd[1]: Stopping dnsmasq - A lightweight DHCP and caching DNS server...
Jun 15 19:29:36 raspberry-pi systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
Jun 15 19:29:36 raspberry-pi systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jun 15 19:29:36 raspberry-pi dnsmasq[11730]: dnsmasq: składnia sprawdzona, jest prawidłowa.
Jun 15 19:29:36 raspberry-pi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
Jun 15 19:30:02 raspberry-pi CRON[11864]: (root) CMD (   PATH="$PATH:/usr/local/bin/" pihole updatechecker local)
Jun 15 19:31:12 raspberry-pi kernel: [ 4311.862902] Under-voltage detected! (0x00050005)
Jun 15 19:31:18 raspberry-pi kernel: [ 4318.102454] Voltage normalised (0x00000000)
Jun 15 19:32:12 raspberry-pi kernel: [ 4372.195259] Under-voltage detected! (0x00070005)
Jun 15 19:32:19 raspberry-pi kernel: [ 4378.437690] Voltage normalised (0x00020002)
Jun 15 19:32:45 raspberry-pi kernel: [ 4404.451224] device wlan0 entered promiscuous mode
Jun 15 19:33:52 raspberry-pi kernel: [ 4472.050487] Under-voltage detected! (0x00070007)
Jun 15 19:33:59 raspberry-pi kernel: [ 4478.269245] Voltage normalised (0x00020002)
Jun 15 19:38:44 raspberry-pi kernel: [ 4763.419588] device wlan0 left promiscuous mode
Jun 15 19:39:01 raspberry-pi CRON[12939]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Jun 15 19:39:06 raspberry-pi systemd[1]: Starting Clean php session files...
Jun 15 19:39:08 raspberry-pi systemd[1]: Started Clean php session files.
Jun 15 19:39:26 raspberry-pi systemd[1]: Stopping dnsmasq - A lightweight DHCP and caching DNS server...
Jun 15 19:39:27 raspberry-pi systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
Jun 15 19:39:27 raspberry-pi systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jun 15 19:39:27 raspberry-pi dnsmasq[13112]: dnsmasq: składnia sprawdzona, jest prawidłowa.
Jun 15 19:39:28 raspberry-pi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
Jun 15 19:40:01 raspberry-pi CRON[13276]: (root) CMD (   PATH="$PATH:/usr/local/bin/" pihole updatechecker local)`
HTTP server work on 8888 port. Port 80 is only for WS.
But no any date on my weewx page. Where am I doing wrong?
Earlier I checked and I got correct answers from my WS:
`1529077389|rtupdate.wunderground.com|GET /weatherstation/updateweatherstation.php?ID=IWROCAW54&PASSWORD=xxxxxxxxx&indoortempf=79.3&tempf=79.5&dewptf=49.5&windchillf=79.5&indoorhumidity=38&humidity=35&windspeedmph=2.9&windgustmph=4.5&winddir=355&absbaromin=29.57&baromin=29.83&rainin=0.00&dailyrainin=0.00&weeklyrainin=0.45&monthlyrainin=0.45&yearlyrainin=-9999&solarradiation=305.84&UV=3&dateutc=2018-6-15%2015:43:3&softwaretype=EasyWeatherV1.2.0&action=updateraw&realtime=1&rtfreq=5 HTTP/1.0|200|568`

**Comment by barcik75** [comment]
Ok, some problems was fixed. I get information from my WS. But still I haven't information on my webpage.
From sysolg:

> Jun 18 17:16:41 raspberry-pi weewx[32616]: engine: Starting main packet loop.
Jun 18 17:16:54 raspberry-pi weewx[32616]: interceptor: MainThread: skipping rain measurement of 0.0: no last rain
Jun 18 17:16:54 raspberry-pi weewx[32616]: interceptor: MainThread: shutting down server thread
Jun 18 17:16:55 raspberry-pi weewx[32616]: engine: Caught unrecoverable exception in engine:
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****  integer division or modulo by zero
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****  Traceback (most recent call last):
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weewx/engine.py", line 871, in main
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      engine.run()
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weewx/engine.py", line 190, in run
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weewx/engine.py", line 223, in dispatchEvent
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      callback(event)
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weewx/engine.py", line 527, in new_loop_packet
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      self.accumulator = self._new_accumulator(event.packet['dateTime'])
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weewx/engine.py", line 637, in _new_accumulator
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      self.archive_interval)
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 281, in startOfInterval
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****      m = int(time_tt.tm_min  // interval_m * interval_m)
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****  ZeroDivisionError: integer division or modulo by zero
Jun 18 17:16:55 raspberry-pi weewx[32616]:     ****  Exiting.

Any idea?

**Comment by barcik75** [comment]
Problem solved
