### ISSUE TITLE
Fresh install of weewx, and weewx-interceptor not finding pcap

### ISSUE THREAD

**Issue by kq6up** [matthewwall/weewx-interceptor#88]
I am just freshly installed Raspberry Pi OS.  v10, and added weewx and whew-interceptor.  weewx does not seem to be able to find pcap.  Tried installing via pip3, but that failed.  See below.

PYTHONPATH=/usr/share/weewx python3.7 /usr/share/weewx/user/interceptor.py  --device=wu-client --mode=sniff --iface=wlan0 --filter="src 10.3.141.99 and dst port 80"
Traceback (most recent call last):
  File "/usr/share/weewx/user/interceptor.py", line 2664, in <module>
    address=options.addr, port=options.port)
  File "/usr/share/weewx/user/interceptor.py", line 728, in __init__
    WUClient.Parser(), handler=WUClient.Handler, **stn_dict)
  File "/usr/share/weewx/user/interceptor.py", line 427, in __init__
    iface, pcap_filter, promiscuous)
  File "/usr/share/weewx/user/interceptor.py", line 465, in __init__
    import pcap
ModuleNotFoundError: No module named 'pcap'

@@@@@@@@@@@@@

So tried to also install with pip3, but failed with this error.  I am stuck, and don't know where to go from here.
pip3 install pypcap
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pypcap
  Downloading 
    
https://files.pythonhosted.org/packages/12/71/a689ca8c6ef4570e105efdc6b46d4ac16cdef7af36a8fbfaff0f6fa2b754/pypcap-1.2.3.tar.gz 
    (136kB) 100% |████████████████████████████████| 143kB 1.4MB/s 
    Complete output from command python setup.py egg_info: pcap.h not 
    found
    
    ---------------------------------------- Command "python setup.py 
egg_info" failed with error code 1 in /tmp/pip-install-yuo7efq5/pypcap/

Thanks,
Chris KQ6UP

**Comment by KC1ELF** [comment]
Same issue.  Any resolution?
