### ISSUE TITLE
help question

### ISSUE THREAD

**Issue by edegraaff** [matthewwall/weewx-interceptor#95]
Hi, i need some help to realise the folowing:
I have an Unit Ventus W830 , it uses ecowitt protocol, and i configured the ventus to send all ecowitt data to 192.168.1.xx on port 4199, this server processes the data in home assistant but ... 

I want to reuse this data to aprs, so my idea was i build an pi with weewx since i understood weewx can push data in the right format to aprs.

i tried to use the weewx-interceptor to listen to see the packages but i failed there. 

 PYTHONPATH=bin python3 ./bin/user/interceptor.py --device=ecowitt-client --mode=sniff --iface=eth0 --filter="src 192.168.1.xx and dst port 4199"

I get this error, while pcap is installed i used :  sudo apt-get install python-libpcap

Traceback (most recent call last):
  File "/home/weewx/bin/user/interceptor.py", line 2664, in <module>
    address=options.addr, port=options.port)
  File "/home/weewx/bin/user/interceptor.py", line 1002, in __init__
    AcuriteBridge.Parser(), handler=AcuriteBridge.Handler, **stn_dict)
  File "/home/weewx/bin/user/interceptor.py", line 427, in __init__
    iface, pcap_filter, promiscuous)
  File "/home/weewx/bin/user/interceptor.py", line 465, in __init__
    import pcap
ModuleNotFoundError: No module named 'pcap'

**Comment by kinwolfqc** [comment]
I get the same error.
